### ISSUE TITLE
gitsue

### ISSUE THREAD

**Issue by janicemin** [ga-dc/wdidc5-project3#71] opened 2015-05-14 14:16 UTC
so yesterday matt and i moved my rails app to a different folder and was able to deploy to heroku. i am getting this error now as i'm trying to push new commits 

```
09:44:40-janicemin~/desktop/wdiproject3/project3/canborrow2 (master)$ git push origin master
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

so i did a git remote -v
`09:57:33-janicemin~/desktop/wdiproject3/project3/canborrow2 (master)$ git remote -v
heroku  https://git.heroku.com/radiant-shelf-5474.git (fetch)
heroku  https://git.heroku.com/radiant-shelf-5474.git (push)`

and that was all there was...

so i did a 
`09:55:27-janicemin~/desktop/wdiproject3/project3/canborrow2 (master)$ git remote add origin https://github.com/janicemin/project3.git`

and i'm got this message:
`09:57:33-janicemin~/desktop/wdiproject3/project3/canborrow2 (master)$ git remote -v
heroku  https://git.heroku.com/radiant-shelf-5474.git (fetch)
heroku  https://git.heroku.com/radiant-shelf-5474.git (push)
origin  https://github.com/janicemin/project3.git (fetch)
origin  https://github.com/janicemin/project3.git (push)
09:57:38-janicemin~/desktop/wdiproject3/project3/canborrow2 (master)$ git push origin master
Username for 'https://github.com': janicemin
Password for 'https://janicemin@github.com': 
To https://github.com/janicemin/project3.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/janicemin/project3.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.`

halp? not sure why i can't push at this point?

**Comment by mattscilipoti** [comment] 2015-05-14 14:24
Could you send the results of `git remote -v` (again), but format it as code?  Use the "Markdown supported" link above and verify via "Preview" tab.

**Comment by mattscilipoti** [comment] 2015-05-14 14:25
What do you think the issue is?

**Comment by janicemin** [comment] 2015-05-14 14:45
I don't really know what the issue is? it didn't have the origin as a path, so i thought by adding it, i would be able to push

**Comment by janicemin** [comment] 2015-05-14 14:46
Please make sure you have the correct access rights
and the repository exists.
09:52:53-janicemin~/desktop/wdiproject3/project3/canborrow2 (master)$ git remote -v
heroku  https://git.heroku.com/radiant-shelf-5474.git (fetch)
heroku  https://git.heroku.com/radiant-shelf-5474.git (push)
09:55:27-janicemin~/desktop/wdiproject3/project3/canborrow2 (master)$ git remote add origin https://github.com/janicemin/project3.git
09:57:28-janicemin~/desktop/wdiproject3/project3/canborrow2 (master)$ git statusOn branch master
nothing to commit, working directory clean
09:57:33-janicemin~/desktop/wdiproject3/project3/canborrow2 (master)$ git remote -v
heroku  https://git.heroku.com/radiant-shelf-5474.git (fetch)
heroku  https://git.heroku.com/radiant-shelf-5474.git (push)
origin  https://github.com/janicemin/project3.git (fetch)
origin  https://github.com/janicemin/project3.git (push)

**Comment by janicemin** [comment] 2015-05-14 14:51
09:57:38-janicemin~/desktop/wdiproject3/project3/canborrow2 (master)$ git push origin master
Username for 'https://github.com': janicemin
Password for 'https://janicemin@github.com': 
To https://github.com/janicemin/project3.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/janicemin/project3.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
09:57:49-janicemin~/desktop/wdiproject3/project3/canborrow2 (master)$ git push
fatal: The current branch master has no upstream branch.
To push the current branch and set the remote as upstream, use

```
git push --set-upstream origin master
```

10:01:15-janicemin~/desktop/wdiproject3/project3/canborrow2 (master)$ git push -- set-upstream origin master
error: src refspec origin does not match any.
error: failed to push some refs to 'set-upstream'

**Comment by mattscilipoti** [comment] 2015-05-14 15:20
Ahhh.  I see.  We chose to use your "canborrow2" repo, instead of your "project3" repo.  Instead of adding the "project3.git" as the origin, you need to create a new GitHub repo for your existing, local "canborrow2" repo.  
- Create a new, blank repo on Github for your project (without readme, etc).
- follow the instructions for adding it as the origin for your existing, local repo (canborrow2).

**Comment by mattscilipoti** [comment] 2015-05-14 15:20
Once it all works, I recommend you delete the old, Project3 repo.

**Comment by mattscilipoti** [comment] 2015-05-14 15:22
Note: I expect you will have to remove the improper origin remote (Project3), in order to add the new one.

**Comment by mattscilipoti** [comment] 2015-05-14 16:29
You have already configured git to use "Project3" as your origin.  You must remove that remote first.  Then assign github's canborrow repo as your origin.

**Comment by janicemin** [comment] 2015-05-14 16:30
so i should git remote rm origin ?

**Comment by janicemin** [comment] 2015-05-14 16:32
yup, got it!

**Comment by janicemin** [comment] 2015-05-14 16:32
sorry for the confusion, some of your emails aren't popping up/page isn't refreshed, so i kept on missing some of your comments. thank you matt!

**Comment by andrewsunglaekim** [comment] 2015-05-14 18:28
I'm going to close this issue, please open another if you feel this hasn't been resolved

**Closed as completed by andrewsunglaekim** 2015-05-14 18:28 UTC
